# Generated by Django 3.0.3 on 2020-03-08 08:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='designation',
            field=models.CharField(default='Software Engineer', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='long_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
