# Generated by Django 3.0.3 on 2020-03-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0002_auto_20200308_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
